# Generated by Django 5.2 on 2025-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
