# Generated by Django 5.2 on 2025-05-12 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_userlog_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
