# Generated by Django 5.2 on 2025-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_facedata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
