# Generated by Django 5.2 on 2025-05-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_userlog_in_time_userlog_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='out_time',
        ),
    ]
