# Generated by Django 5.2 on 2025-05-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_attendancelog_remove_userlog_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.facedata')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
    ]
