# Generated by Django 5.2 on 2025-05-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_attendance_delete_attendancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
