# Generated by Django 5.2 on 2025-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0008_alter_attendance_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedata',
            name='name',
        ),
        migrations.AddField(
            model_name='facedata',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facedata',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facedata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
