# Generated by Django 5.2 on 2025-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0009_remove_facedata_name_facedata_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
