# Generated by Django 5.2 on 2025-06-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0010_facedata_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.facedata')),
            ],
        ),
    ]
