# Generated by Django 5.2 on 2025-06-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0011_attendancelogentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelogentry',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='attendancelogentry',
            name='date',
        ),
    ]
